export enum ResourceType {
	AI = 'ai',
	IMAGE = 'image',
	BUSINESS = 'business',
	CONVERT = 'convert',
	GENERATE = 'generate',
	CRYPTO = 'crypto',
	OPERATOR = 'operator',
	STORAGE = 'storage',
	SCHEDULER = 'scheduler',
	TEXT = 'text',
	CHART = 'chart',
	CODE = 'code',
	FACTURX = 'facturx',
	CALCULATE = 'calculate',
	DATE_AND_TIME = 'dateandtime',
	PDF = 'pdf',
	USER = 'user',
}
