export enum OperationType {
	COMPRESS = 'compress',
	COUNT = 'count',
	CREATE = 'create',
	DECRYPT = 'decrypt',
	DOCX_TO_PDF = 'docx-to-pdf',
	DRAW = 'draw',
	ENCRYPT = 'encrypt',
	HTML = 'html',
	MARKDOWN_TO_PDF = 'markdownstringtopdf',
	METADATA = 'metadata',
	MERGE = 'merge',
	PAGES = 'pages',
	BASE64 = 'base64',
	PDF_TO_IMAGE = 'pdf-to-image',
	SPLIT = 'split',
	WATERMARK = 'watermark',
}
