export enum OperationType {
	ADVANCED_OCR = 'advancedocr',
	CHECK_CONTENT_POLICY = 'checkcontentpolicy',
	DETECT_ADULT_CONTENT = 'detectadultcontent',
	DETECT_BRAND = 'detectbrand',
	DETECT_COLOR = 'detectcolor',
	DETECT_EMAIL_TYPE = 'detectemailtype',
	DETECT_FACE = 'detectface',
	ENTITY_DETECTION = 'entitydetection',
	EXTRACT_CONTACT_INFORMATION = 'extractcontactinformation',
	EXTRACT_FROM_TEXT = 'extract-from-text',
	FUZZY_MATCH = 'fuzzy-match',
	GENERATE_IMAGE = 'generateimage',
	GENERATE_JAVASCRIPT_CODE = 'generatejavascriptcode',
	GENERATE_PYTHON_CODE = 'generatepythoncode',
	LANGUAGE_DETECTION = 'languagedetection',
	MOOD_DETECTION = 'mooddetection',
	PDF_OCR = 'pdfocr',
	PICTURE_OBJECT_RECOGNITION = 'pictureobjectrecognition',
	PICTURE_TEXT_RECOGNITION = 'picturetextrecognition',
	REDACT_PDF = 'redact-pdf',
	REMOVE_BACKGROUND = 'removebg',
	TOO_LONG_TO_READ = 'toolongtoread',
	TRANSCRIBE = 'transcribe',
	TRANSLATE = 'translate',
}
